<script>
    import { Heading, A } from 'flowbite-svelte';
</script>

<div class="px-4 mb-4">
    <Heading tag="h2" class="mb-4">Terms and Conditions</Heading>
    <p class="mb-3">
        These terms and conditions govern your use of this website; by using this website, you
        accept these terms and conditions in full. If you disagree with these terms and conditions
        or any part of these terms and conditions, you must not use this website.
    </p>
    <p>
        This website uses local browser storage. By using this website and agreeing to these terms
        and conditions, you consent to BioRand's use of local browser storage in accordance with the
        terms of BioRand's privacy policy.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Intellectual Property Rights</Heading>
    <p class="mb-3">
        BioRand owns the intellectual property rights in the website design and associated software
        and all rights are reserved. All website content including generated randomizers, images,
        profiles, and user-submitted material are assumed to have been placed in the public domain
        and can be freely reproduced for non-commercial purposes.
    </p>
    <p class="mb-3">
        Content generated from BioRand can not be sold for commercial gain and must be redistributed
        freely with acknoledgement of BioRand.
    </p>
    <p>
        Content generated by BioRand contains modified files from Resident Evil (2023) under fair
        use. Resident Evil 4 and its associated content is owned and licensed by Capcom Co., Ltd.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Acceptable use</Heading>
    <p class="mb-3">
        You must not use this website in any way that causes, or may cause, damage to the website or
        impairment of the availability or accessibility of the website; or in any way which is
        unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal,
        fraudulent or harmful purpose or activity.
    </p>
    <p class="mb-3">
        You must not use this website to copy, store, host, transmit, send, use, publish or
        distribute any material which consists of (or is linked to) any spyware, computer virus,
        Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.
    </p>
    <p class="mb-3">
        You must not conduct any systematic or automated data collection activities (including
        without limitation scraping, data mining, data extraction and data harvesting) on or in
        relation to this website without BioRand’s express written consent.
    </p>
    <p class="mb-3">
        You must not use this website to transmit or send unsolicited commercial communications.
    </p>
    <p>
        You must not use this website for any purposes related to marketing without BioRand’s
        express written consent.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Restricted access</Heading>
    <p class="mb-3">
        Access to certain areas of this website is restricted. BioRand reserves the right to
        restrict access to other areas of this website, or indeed this entire website, at BioRand’s
        discretion.
    </p>
    <p class="mb-3">
        BioRand provides registered users with additional functionality and access to restricted
        areas of this website using an account login. When registering, you must provide an online
        user name and a personal email address by which you can be contacted when required. You must
        ensure that your your account is used solely by you or someone acting under either on your
        behalf or under your supervision. Multiple login accounts are not permitted.
    </p>
    <p class="mb-3">
        If there is doubt about the true identity of a registered user, or it appears that they do
        not have a genuine interest in using the site for its intended purpose, or it appears that a
        person has multiple accounts, access may be restricted until the identity and/or intention
        of the user of the affected account(s) has been established to BioRand's satisfaction.
    </p>
    <p>
        BioRand may disable your user account in BioRand’s sole discretion without notice or
        explanation.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">User content</Heading>
    <p class="mb-3">
        In these terms and conditions, “your user content” means material (including without
        limitation text, images, audio material, video material and audio-visual material) that you
        submit to this website, for whatever purpose.
    </p>
    <p class="mb-3">
        You grant to BioRand a worldwide, irrevocable, non-exclusive, royalty-free license to use,
        reproduce, adapt, publish, translate and distribute your user content in any existing or
        future media.
    </p>
    <p class="mb-3">
        Your user content must not be illegal or unlawful, must not infringe any third party's legal
        rights, and must not be capable of giving rise to legal action whether against you or
        BioRand or a third party (in each case under any applicable law).
    </p>
    <p class="mb-3">
        You must not submit any user content to the website that is or has ever been the subject of
        any threatened or actual legal proceedings or other similar complaint.
    </p>
    <p class="mb-3">
        BioRand reserves the right to edit or remove any material submitted to this website, or
        stored on BioRand’s servers, or hosted or published upon this website.
    </p>
    <p>
        Notwithstanding BioRand’s rights under these terms and conditions in relation to user
        content, BioRand does not undertake to monitor the submission of such content to, or the
        publication of such content on, this website.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">No warranties</Heading>
    <p class="mb-3">
        This website is provided “as is” without any representations or warranties, express or
        implied. BioRand makes no representations or warranties in relation to this website or the
        information and materials provided on this website.
    </p>
    <p class="mb-3">
        Without prejudice to the generality of the foregoing paragraph, BioRand does not warrant
        that:
    </p>
    <ul class="mb-3">
        <li>this website will be constantly available, or available at all; or</li>
        <li>the information on this website is complete, true, accurate or non-misleading.</li>
    </ul>
    <p>Nothing on this website constitutes, or is meant to constitute, advice of any kind.</p>

    <Heading tag="h4" class="mt-4 mb-2">Limitations of liability</Heading>
    <p class="mb-3">
        BioRand will not be liable to you (whether under the law of contact, the law of torts or
        otherwise) in relation to the contents of, or use of, or otherwise in connection with, this
        website:
    </p>
    <ul class="mb-3">
        <li>for any indirect, special or consequential loss; or</li>
        <li>
            for any business losses, loss of revenue, income, profits or anticipated savings, loss
            of contracts or business relationships, loss of reputation or goodwill, or loss or
            corruption of information or data.
        </li>
    </ul>
    <p>
        These limitations of liability apply even if BioRand has been expressly advised of the
        potential loss.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Exceptions</Heading>
    <p class="mb-3">
        Nothing in this website disclaimer will exclude or limit any warranty implied by law that it
        would be unlawful to exclude or limit; and nothing in this website disclaimer will exclude
        or limit BioRand’s liability in respect of any:
    </p>
    <ul>
        <li>death or personal injury caused by BioRand’s negligence;</li>
        <li>fraud or fraudulent misrepresentation on the part of BioRand; or</li>
        <li>
            matter which it would be illegal or unlawful for BioRand to exclude or limit, or to
            attempt or purport to exclude or limit, its liability.
        </li>
    </ul>

    <Heading tag="h4" class="mt-4 mb-2">Reasonableness</Heading>
    <p class="mb-3">
        By using this website, you agree that the exclusions and limitations of liability set out in
        this website disclaimer are reasonable.
    </p>
    <p>If you do not think they are reasonable, you must not use this website.</p>

    <Heading tag="h4" class="mt-4 mb-2">Other parties</Heading>
    <p>
        You agree that the limitations of warranties and liability set out in this website
        disclaimer will protect BioRand’s officers, employees, agents, subsidiaries, successors,
        assigns and sub-contractors as well as BioRand.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Unenforceable provisions</Heading>
    <p>
        If any provision of this website disclaimer is, or is found to be, unenforceable under
        applicable law, that will not affect the enforceability of the other provisions of this
        website disclaimer.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Indemnity</Heading>
    <p>
        You hereby indemnify BioRand and undertake to keep BioRand indemnified against any losses,
        damages, costs, liabilities and expenses (including without limitation legal expenses and
        any amounts paid by BioRand to a third party in settlement of a claim or dispute on the
        advice of BioRand’s legal advisers) incurred or suffered by BioRand arising out of any
        breach by you of any provision of these terms and conditions, or arising out of any claim
        that you have breached any provision of these terms and conditions.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Breaches of these terms and conditions</Heading>
    <p>
        Without prejudice to BioRand’s other rights under these terms and conditions, if you breach
        these terms and conditions in any way, BioRand may take such action as BioRand deems
        appropriate to deal with the breach, including suspending your access to the website,
        prohibiting you from accessing the website, blocking computers using your IP address from
        accessing the website, contacting your internet service provider to request that they block
        your access to the website and/or bringing court proceedings against you.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Variation</Heading>
    <p>
        BioRand may revise these terms and conditions from time-to-time. Revised terms and
        conditions will apply to the use of this website from the date of the publication of the
        revised terms and conditions on this website. Please check this page regularly to ensure you
        are familiar with the current version.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Assignment</Heading>
    <p class="mb-3">
        BioRand may transfer, sub-contract or otherwise deal with BioRand’s rights and/or
        obligations under these terms and conditions without notifying you or obtaining your
        consent.
    </p>
    <p>
        You may not transfer, sub-contract or otherwise deal with your rights and/or obligations
        under these terms and conditions.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Severability</Heading>
    <p>
        If a provision of these terms and conditions is determined by any court or other competent
        authority to be unlawful and/or unenforceable, the other provisions will continue in effect.
        If any unlawful and/or unenforceable provision would be lawful or enforceable if part of it
        were deleted, that part will be deemed to be deleted, and the rest of the provision will
        continue in effect.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Entire agreement</Heading>
    <p>
        These terms and conditions constitute the entire agreement between you and BioRand in
        relation to your use of this website, and supersede all previous agreements in respect of
        your use of this website.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Law and jurisdiction</Heading>
    <p>
        These terms and conditions will be governed by and construed in accordance with the law of
        England and Wales, and any disputes relating to these terms and conditions will be subject
        to the [non-]exclusive jurisdiction of the courts of England and Wales.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">Credit</Heading>
    <p>
        This document was created using a Contractology template available at
        http://www.freenetlaw.com.
    </p>

    <Heading tag="h4" class="mt-4 mb-2">BioRand’s details</Heading>
    <p class="mb-3">
        The registered domain name for BioRand is <a href="https://biorand.net">biorand.net</a> and all
        rights are reserved by the domain name owner.
    </p>
    <p>
        You can contact BioRand by email to <A href="mailto:support@biorand.net"
            >support@biorand.net</A
        >.
    </p>
</div>
