@HostAddress = http://localhost:10285
@Authorization = Bearer 56bcb5e55dd8a599d623bc7a60a102e6

GET http://localhost:10285/user/ HTTP/1.1
Authorization: {{Authorization}}

###

GET http://localhost:10285/user/?sort=Name HTTP/1.1
Authorization: {{Authorization}}
