@HostAddress = http://localhost:10285

POST {{HostAddress}}/auth/register
content-type: application/json

{
    "email": "intelorca@gmail.com",
    "name": "IntelOrca"
}

###

POST {{HostAddress}}/auth/signin
content-type: application/json

{
    "email": "intelorca@gmail.com"
}

###

POST {{HostAddress}}/auth/signin
content-type: application/json

{
    "email": "intelorca@gmail.com",
    "code": "603159"
}
