GET http://localhost:10285/api/profile/ HTTP/1.1
Authorization: Bearer 3c1cdd28dc812b99c4c5245c38c92550

###

GET http://localhost:10285/api/profile/search?q=h&sort=StarCount HTTP/1.1
Authorization: Bearer 3c1cdd28dc812b99c4c5245c38c92550
