@HostAddress = http://localhost:10285
@Authorization = Bearer 56bcb5e55dd8a599d623bc7a60a102e6

GET {{HostAddress}}/profile/definition/

###

GET {{HostAddress}}/profile/
Authorization: {{Authorization}}

###

GET {{HostAddress}}/profile/search?q=balance
Authorization: {{Authorization}}

###

GET {{HostAddress}}/profile/search?user=7rayD
Authorization: {{Authorization}}

###

GET {{HostAddress}}/profile/1
Authorization: {{Authorization}}

###

POST {{HostAddress}}/profile/7/star
Authorization: {{Authorization}}

###

DELETE {{HostAddress}}/profile/7/star
Authorization: {{Authorization}}
