name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Restore
      run: dotnet restore src/biorand-re4r
    - name: Build
      run: dotnet publish src/biorand-re4r -c release -r win-x64 -o out -p:PublishSingleFile=true
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: biorand4
        path: out/biorand-re4r
